<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SearchResults</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a283a514-db9d-446b-a613-fc91f51d348c</testSuiteGuid>
   <testCaseLink>
      <guid>aa1c15e0-e73b-4c89-9ae2-d45b56b9a75d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/01_General/01_NoResultsFound</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d3ed2b28-24e5-4491-858f-fbbe68d22941</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/01_General/02_DefaultView</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0c644726-bec2-4cd8-a17f-26fbca2c4748</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/01_General/03_UpdateCriteria</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1a01ff1-ccdd-48e5-8dea-55fa6a085347</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30e3c33b-d362-40ba-86c1-887d2daa96e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>659abd39-c05f-435e-9e98-7eca3e794ac8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/01_HotelGallery/01_ClickNextPrevious_CheckImageCount</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>737c25d2-eb10-45cc-8401-f28362b4d799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/01_HotelGallery/02_ClickFirstImage_CheckAppendedParameters</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea44377d-c57f-40bf-af08-47bc9f76944b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>493ce5de-9a28-4675-bb5f-7c648170de81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/01_HotelGallery/03_ClickAnImage_CheckAppendedParameters</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b69f209-dd09-42c9-9f62-461e9dcc4d95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4c9c273-1eb2-4561-94a5-d9ca2589fca4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0946a678-1095-4a1a-b05d-4a0870958df7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/01_HotelGallery/04_ClickPreviousOnFirstImage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f295d60d-9e44-49a6-bc19-cc46f9e0d298</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76a5d62f-1272-43cb-994d-de5e891d5b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c525871-cf46-4f9a-a704-3a177ddfdf48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/01_HotelGallery/05_ClickNextOnLastImage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>832af891-4f1a-43eb-9551-3ae4b5c33844</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20fefbd-96cd-46ba-883b-761124a1bf1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a57e7896-7be6-4ebf-b4ca-2fb761824c27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/01_HotelGallery/06_ClickMagnifierToOpenOverlay---</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc8ca7cd-0903-4b25-aedd-17a24f281a84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d76ceae-30b5-4503-882e-99ad85d4c1c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>982dccdd-ec4c-453b-8e4f-ec53adcaf2ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/02_HotelBox/01_ClickHotelName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fadc986b-88eb-48ce-9138-7de037ba2b4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03281a68-bca1-4e64-8a0b-2b61b806d5d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/02_HotelBox/02_ClickDestination</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62f177aa-010f-465e-b04a-171f902e3411</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78afd717-570a-461c-aaf2-df4cb7c7acff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/02_HotelBox/03_CheckDescription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d9500b-4599-4255-a63c-91b0a3fc35e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25452cbd-c44d-4d02-be24-49fbeecf451b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/02_HotelBox/04_CheckRatesNReviews</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20f2e2c0-8dbe-4a81-a6e9-d3b0f8eeda33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41a3f6e3-02bc-49e6-8037-9f1ccf8b0529</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/02_HotelBox/05_BookNowBtn</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5306733-0f3e-4a88-b87e-7c4eeeacd317</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acccd803-e397-49b7-a343-ec8a599a8522</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/02_HotelDetails/02_HotelBox/06_ChangeDatesBtn</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad79aaa-003a-4517-ad36-4f2a24517815</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35dfc190-7b00-453c-9f5e-23615cdcf988</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
