<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SearchResults</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a283a514-db9d-446b-a613-fc91f51d348c</testSuiteGuid>
   <testCaseLink>
      <guid>6f9ab5f8-1e4f-42e7-9e7f-049605a93c41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/SRP_010101_HotelListing_NoResultsFound</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c503874-38e2-4586-8fd1-b229c08a5065</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/SRP_010201_HotelListing_DefaultView</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0f40e3d9-b1f3-44b3-81a8-387f41563f79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/01_HotelListing/SRP_010202_HotelListing_UpdateCriteria</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1a01ff1-ccdd-48e5-8dea-55fa6a085347</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30e3c33b-d362-40ba-86c1-887d2daa96e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01778a72-3bc5-4fd5-a8b2-43f8c24c4c6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/02_HotelDetails/020102_HotelGallery_ClickFirstImage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea44377d-c57f-40bf-af08-47bc9f76944b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6631d4a-fc65-4508-850d-af7028baa2aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/02_HotelDetails/020103_HotelGallery_ClickAnyOtherImage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b69f209-dd09-42c9-9f62-461e9dcc4d95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4c9c273-1eb2-4561-94a5-d9ca2589fca4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b78601d-8d10-48ca-86e3-551dc395b094</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SRP_SearchResults_Desktop/02_HotelDetails/020101_HotelGallery_ClickNextPrevious_CheckImageCount</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
