<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Location</name>
   <tag></tag>
   <elementGuidId>fbcc0837-781e-4ae5-a9ac-af7dc1bc79e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[starts-with(@class,'apps-search-bar-form')]//div[contains(@class,'textinput')]//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ui-textinput__field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-textinput__field</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Where would you like to go?+</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sc-layout__container&quot;]/div[@class=&quot;ui-container-full&quot;]/main[1]/div[@class=&quot;sc-stage sc-stage--variant-1 sc-stage--&quot;]/div[@class=&quot;sc-stage__content&quot;]/div[@class=&quot;sc-stage__search-bar-container&quot;]/div[@class=&quot;apps-searchbar&quot;]/div[@class=&quot;apps-search-bar&quot;]/form[@class=&quot;apps-search-bar-form&quot;]/div[@class=&quot;apps-search-bar-form__content&quot;]/div[@class=&quot;apps-search-bar-form__elements&quot;]/div[@class=&quot;apps-search-bar-form__elements-wrapper&quot;]/div[1]/div[@class=&quot;apps-search-bar-input-field apps-search-bar-input-field__active&quot;]/div[@class=&quot;ui-textinput ui-textinput--flat container-icon-mobaile ui-textinput-icon&quot;]/input[@class=&quot;ui-textinput__field&quot;]</value>
   </webElementProperties>
</WebElementEntity>
