<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Currency_Selected</name>
   <tag></tag>
   <elementGuidId>1bfd16d3-45c6-4cfa-b52b-ba6c0e550b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header//*[@class='sc-currency-switcher']//option[@selected]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
