<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchTrigger_Icon</name>
   <tag></tag>
   <elementGuidId>e4925d19-05fe-4ead-ace0-496dbb42d71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header//div[contains(@class,'sc-search-trigger--desktop')]/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
