<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Guests_Children_Minus</name>
   <tag></tag>
   <elementGuidId>47fb7697-35dd-450d-9f23-f9b680bb7c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[starts-with(@class,'apps-search-bar-form')]//span[contains(text(),'hildren')]/ancestor::div[@class='ui-guests-popup-row']//button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Guests-count</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Guests-count</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 Guests+</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sc-layout__container&quot;]/div[@class=&quot;ui-container-full&quot;]/main[1]/div[@class=&quot;sc-stage sc-stage--variant-1 sc-stage--&quot;]/div[@class=&quot;sc-stage__content&quot;]/div[@class=&quot;sc-stage__search-bar-container&quot;]/div[@class=&quot;apps-searchbar&quot;]/div[@class=&quot;apps-search-bar&quot;]/form[@class=&quot;apps-search-bar-form&quot;]/div[@class=&quot;apps-search-bar-form__content&quot;]/div[@class=&quot;apps-search-bar-form__elements&quot;]/div[@class=&quot;apps-search-bar-form__elements-wrapper&quot;]/div[1]/div[@class=&quot;apps-search-bar__select-fields&quot;]/div[@class=&quot;ui-guests-field&quot;]/div[@class=&quot;ui-search-field__labelbottom&quot;]/div[@class=&quot;Guests-count&quot;]</value>
   </webElementProperties>
</WebElementEntity>
